
all:	gallery;

gallery:
	@echo Generating gallery with fgallery
	~/opt/fgallery-1.6/fgallery -s -t -j 4 images/ recon-wireless-mea-culpa/
	@echo "Don't forget to apply patch to index.js in recon-wireless-mea-culpa/"
